# Install the Netlify Next.js plugin
npm install @netlify/plugin-nextjs

# Create a netlify.toml config file
echo '[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
' > netlify.toml
